Add freespace checking and release/debug build options

diff --git a/compileClang b/compileClang
--- a/compileClang
+++ b/compileClang
@@ -1,41 +1,103 @@
 #!/bin/bash
 
 CLANG_COMP_DIR=/tmp/clang
+releaseOnly=true
+gigsNeeded=3
 
-mkdir -p $CLANG_COMP_DIR 
-pushd $CLANG_COMP_DIR 
+parseOptions()
+{
+    case "$1" in
+        releaseOnly)
+            releaseOnly=true
+            gigsNeeded=3
+        ;;
+        debugAssert)
+            releaseOnly=false
+            gigsNeeded=30
+        ;;
+        *)
+            echo "Usage: ${0##*/} {releaseOnly|debugAssert}"
+            exit 1
+        ;;
+    esac
+}
 
-if [[ $? != 0 ]]
-then
-    exit -1
-fi
+checkFreeSpace()
+{
+    local freeSpace=$(df -h /tmp/ --output=avail| tail -1)
+    local regex="([0-9]+)([GT])"
+    if [[ $freeSpace =~ $regex ]];
+    then
+        local unit="${BASH_REMATCH[2]}"
+        if [[ $unit == "T" ]];
+        then
+            echo "Terrabytes of free space OK"
+        else
+            local space="${BASH_REMATCH[1]}"
+            if [[ "${gigsNeeded}" -gt "${space}" ]];
+            then
+                echo "Error: Free space: ${space}G is less then the required ${gigsNeeded}G! Exiting."
+                exit -1
+            else
+                echo "Free space: ${space}G. OK"
+            fi 
+        fi
+    else
+        echo "Error: Less then 1G of free space! Exiting."
+        exit -1
+    fi
+}
+
+main()
+{
+    parseOptions "$@"
+    checkFreeSpace
+
+    mkdir -p $CLANG_COMP_DIR 
+    pushd $CLANG_COMP_DIR 
 
 
-#Checkout LLVM: 
-svn co http://llvm.org/svn/llvm-project/llvm/trunk llvm
+    if [[ $? != 0 ]]
+    then
+        echo "Error: Failed to pushd! Exiting."
+        exit -1
+    fi
+
+    #Checkout LLVM: 
+    svn co http://llvm.org/svn/llvm-project/llvm/trunk llvm
+
+    #Checkout Clang:
+    pushd llvm/tools
+    svn co http://llvm.org/svn/llvm-project/cfe/trunk clang
+    popd
+
+    #Checkout extra Clang Tools: (optional) 
+    pushd llvm/tools/clang/tools
+    svn co http://llvm.org/svn/llvm-project/clang-tools-extra/trunk extra
+    popd
+
+    #Checkout Compiler-RT:
+    pushd llvm/projects
+    svn co http://llvm.org/svn/llvm-project/compiler-rt/trunk compiler-rt
+    popd
+
+    #Build LLVM and Clang:
+    mkdir build #(for building without polluting the source dir)
+    pushd build
+
+        if [[ "$releaseOnly" = true ]];
+        then
+            ../llvm/configure --enable-optimized --disable-assertions
+            make ENABLE_OPTIMIZED=1 -j 8
+        else
+            # Debug + Assert
+            ../llvm/configure
+            make -j 8
+        fi
+    popd
 
 
-#Checkout Clang:
-pushd llvm/tools
-svn co http://llvm.org/svn/llvm-project/cfe/trunk clang
-popd
+    popd
+}
 
-#Checkout extra Clang Tools: (optional) 
-pushd llvm/tools/clang/tools
-svn co http://llvm.org/svn/llvm-project/clang-tools-extra/trunk extra
-popd
-
-#Checkout Compiler-RT:
-pushd llvm/projects
-svn co http://llvm.org/svn/llvm-project/compiler-rt/trunk compiler-rt
-popd
-
-#Build LLVM and Clang:
-mkdir build #(for building without polluting the source dir)
-pushd build
-../llvm/configure
-make -j 8
-popd
-
-
-popd
+main "$@"
